### ISSUE TITLE
I can't do Maven install when the project has a Custom XPath Function

### ISSUE THREAD

**Issue by IsabelLeon** [TIBCOSoftware/bw6-plugin-maven#132]
I'm working in a BWCE 2.3.2 project and Plugin Maven 1.3.0. I can't do a Maven Install when I add a Custom XPath Function to the project. 

What do i have to do to resolve this problem?

I can run correctly the project in my local enviroment, in Business Studio. 
I need to do "Maven install" to generate .ear. Because my project has some maven dependencies. 
I can generate .ear from Business Studio in this way i add the Custom XPath Funcions to .ear but the maven depedencies.

I see these errors: 

[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ MyCustomXPathFunctions ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to C:\datos\labarqbpm\GITv1\multi-processes-servers-antares\MyCustomXPathFunctions\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/datos/labarqbpm/GITv1/multi-processes-servers-antares/MyCustomXPathFunctions/src/mycustomxpathfunctions/CustomFunctions.java:[5,44] package com.tibco.xml.cxf.common.annotations does not exist
[ERROR] /C:/datos/labarqbpm/GITv1/multi-processes-servers-antares/MyCustomXPathFunctions/src/mycustomxpathfunctions/CustomFunctions.java:[6,44] package com.tibco.xml.cxf.common.annotations does not exist
[ERROR] /C:/datos/labarqbpm/GITv1/multi-processes-servers-antares/MyCustomXPathFunctions/src/mycustomxpathfunctions/CustomFunctions.java:[7,44] package com.tibco.xml.cxf.common.annotations does not exist
[ERROR] /C:/datos/labarqbpm/GITv1/multi-processes-servers-antares/MyCustomXPathFunctions/src/mycustomxpathfunctions/CustomFunctions.java:[9,2] cannot find symbol
  symbol: class XPathFunctionGroup
[ERROR] /C:/datos/labarqbpm/GITv1/multi-processes-servers-antares/MyCustomXPathFunctions/src/mycustomxpathfunctions/CustomFunctions.java:[12,10] cannot find symbol
  symbol:   class XPathFunction
  location: class mycustomxpathfunctions.CustomFunctions
[ERROR] /C:/datos/labarqbpm/GITv1/multi-processes-servers-antares/MyCustomXPathFunctions/src/mycustomxpathfunctions/CustomFunctions.java:[19,10] cannot find symbol
  symbol:   class XPathFunction
  location: class mycustomxpathfunctions.CustomFunctions
[ERROR] /C:/datos/labarqbpm/GITv1/multi-processes-servers-antares/MyCustomXPathFunctions/src/mycustomxpathfunctions/CustomFunctions.java:[31,10] cannot find symbol
  symbol:   class XPathFunction
  location: class mycustomxpathfunctions.CustomFunctions
[ERROR] /C:/datos/labarqbpm/GITv1/multi-processes-servers-antares/MyCustomXPathFunctions/src/mycustomxpathfunctions/CustomFunctions.java:[40,10] cannot find symbol
  symbol:   class XPathFunction
  location: class mycustomxpathfunctions.CustomFunctions
[INFO] 8 errors 

....

Regards Isabel.

**Comment by HiteshNembhwani** [comment]
@IsabelLeon could you please try the attached project and see if it works for you? I'm able to package an application using custom XPath function using BWCE 2.3.2 and Maven 1.3.1 versio
[TestCXFUsingMaven.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/1722766/TestCXFUsingMaven.zip)
n.

**Comment by IsabelLeon** [comment]
Hi, 
I have able to package an application using custom XPath function using BWCE 2.3.2 and Maven 1.3.1 versión too with a new and simple Project. So I've reviewed my project and corrected it. Sorry for the inconveniences. 

Regards Isabel

**Comment by IsabelLeon** [comment]
Thanks for your attention

**Comment by HiteshNembhwani** [comment]
thanks for the confirmation @IsabelLeon, closing the issue.
